### ISSUE TITLE
Which version of tensorflow was used in this implementation?

### ISSUE THREAD

**Issue by dragon9001** [berkandemirel/attributes2classname#1]
Hi there,
I would love to reproduce your experiment.
Could you please give the versions of the dependency libraries?

**Comment by berkandemirel** [comment]
Hi,
You can find the list of the versions of the dependency libraries below:

scipy==0.19.0
tflearn==0.3.1
numpy==1.13.0
easydict==1.6
tensorflow==1.0.1
matplotlib==1.5.1
